FROM node:24.14.0 as builder

WORKDIR /build

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json

RUN npm install

COPY . .

RUN npm run build

FROM node:24.14.0 as runnder

RUN npm install -g @google/gemini-cli@latest

WORKDIR /app

COPY --from=builder /build/dist ./dist
COPY --from=builder /build/node_modules ./node_modules
COPY --from=builder /build/package.json ./package.json
COPY --from=builder /build/tsconfig.json ./tsconfig.json
COPY --from=builder /build/.env.docker ./.env


EXPOSE 3000

ENTRYPOINT ["sh", "-c", "npm run start:dev"]